name: Lint

on:
  workflow_run:
    workflows: ["Prettier"]  # Name of the Prettier workflow
    types:
      - completed  # Trigger this workflow when the Prettier Check is completed

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd tests
          npm install
          
      - name: Run Lint
        run: |
          cd tests
          npm run lint
