name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Lint
        run: |
          cd tests
          npm run lint
