name: Prettier

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Install dependencies
        run: |
          cd tests
          npm install
          
      - name: Run Prettier
        run: |
          cd tests
          npm run pretty
